#spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#spring.datasource.url=jdbc:log4jdbc:mysql://localhost:3306/myapp?serverTimezone=UTC&characterEncoding=UTF-8
#spring.datasource.username=root
#spring.datasource.password=1234
spring:
  datasource:
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:log4jdbc:mysql://localhost:3306/myapp?serverTimezone=UTC&characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3306/myapp?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234

#server:
#  error:
#    whitelabel:
#      enabled: false

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        order_inserts: true
        order_updates: true
    open-in-view: true
#    open-in-view: false

logging:
  level:
#    org.hibernate.SQL: error
    org.hibernate.type: trace

# # register p6logfactory to log jdbc events
# decorator.datasource.p6spy.enable-logging=true
# # Use com.p6spy.engine.spy.appender.MultiLineFormat instead of com.p6spy.engine.spy.appender.SingleLineFormat
# decorator.datasource.p6spy.multiline=true
# # Use logging for default listeners [slf4j, sysout, file, custom]
# decorator.datasource.p6spy.logging=slf4j
# # Log file to use (only with logging=file)
# decorator.datasource.p6spy.log-file=spy.log
# # Class file to use (only with logging=custom). The class must implement com.p6spy.engine.spy.appender.FormattedLogger
# decorator.datasource.p6spy.custom-appender-class=my.custom.LoggerClass
# # Custom log format, if specified com.p6spy.engine.spy.appender.CustomLineFormat will be used with this log format
# decorator.datasource.p6spy.log-format=
# # Use regex pattern to filter log messages. If specified only matched messages will be logged.
# decorator.datasource.p6spy.log-filter.pattern=
# # Report the effective sql string (with '?' replaced with real values) to tracing systems.
# # NOTE this setting does not affect the logging message.
# decorator.datasource.p6spy.tracing.include-parameter-values=true

#decorator:
#  datasource:
#    p6spy:
#      enable-logging: true
#      multiline: true
