### v1/simple-orders
GET http://localhost:8080/api/v1/simple-orders
Accept: application/json

### v2/simple-orders
GET http://localhost:8080/api/v2/simple-orders
Accept: application/json

### /api/v3/simple-orders
GET http://localhost:8080/api/v3/simple-orders
Accept: application/json

### /api/v4/simple-orders
GET http://localhost:8080/api/v4/simple-orders
Accept: application/json
